CHZZK-Study/HOWMeet-Frontend

.github/workflows/main.yml

ci,cd를 위한 yml 파일 생성
<br/>
<br/>
ci/cd를 위해 github action과 aws s3, cloudfront를 연동했습니다.
이게 맞는지 확신이 들지 않기때문에 컨펌 부탁드립니다...
제가 추가한 yml 파일에 없는 aws-credential 내용이 위 사진에는 있는데, 필요한 사항인지 잘 모르겠습니다...
<br/>

[CHORE/HM-66] CI/CD yml 추가

---

public/assets/icons/calendar/dashed.svg
public/assets/icons/calendar/next.svg
public/assets/icons/calendar/prev.svg
src/components/bottomsheet/Calendar.tsx
src/components/bottomsheet/EndDate.tsx
src/styles/components/bottomsheet/bottomsheet.ts

[Feat/HM-93] 달력 관련 기능 수정

---

public/assets/icons/button/create-room-plus.svg
public/assets/icons/index.ts
src/components/common/Header.tsx
src/components/roomlist/RoomItem.tsx
src/components/roomlist/RoomList.tsx
src/constants/title.ts
src/pages/MeetingListPage.tsx
src/styles/components/container.ts
src/styles/theme.ts

참여중이 방 리스트 조회 페이지 UI를 구현했습니다.
<br/>
<br/>
**_[ 방 목록 조회 페이지 ]_**
저번 말씀드렸던 방 리스트 height에 %가 적용되지 않았던 이슈를 우선 vh로 해결했는데 괜찮을지.. 다른분들 생각은 어떠실까요 ?!
<br/>

[Feat/HM-90]

---

src/apis/notification.api.ts
src/lib/notification.ts
src/types/notification.ts

> 알림 API 연동
- vapid key 조회 API 연동
- fcm 토큰 등록 API 연동
<br/>
<br/>
<br/>

[API/HM-155]: 알림 API 연동

---

.github/workflows/main.yml
src/pages/NewMeetingNonMemberPage.tsx

ci,cd 오타 수정 했습니다.
<br/>
<br/>
<br/>

[Style/HM-54] ci,cd 오타 수정

---

src/apis/instance.ts
src/apis/notification.api.ts
src/pages/SelectPage.tsx

- 토큰 post 오류 수정
- import 오류 수정
<br/>
<br/>
<br/>

[FIX/HM-155]: 토큰 post 오류 수정

---

src/apis/user.api.ts
src/hooks/useSocialLogin.ts
src/pages/SelectPage.tsx

- 멤버 추가 api 연동
-> 소셜 로그인 직후 멤버 추가 호출 -> 실패 시 로그아웃 처리했습니다.
<br/>
<br/>
<br/>

[API/HM-155]: 멤버 추가 api 연동

---

src/App.tsx
src/components/meeting/result/AttendStatusHeader.tsx
src/components/meeting/result/ResultBottomSheet.tsx
src/components/meeting/result/ResultInfoComp.tsx
src/components/meeting/result/ResultTimeSelectModal.tsx
src/components/meeting/select/SelectableTimeTable.tsx
src/components/meeting/timetable/BaseTimeTable.tsx
src/components/meeting/timetable/ResultTimeCell.tsx
src/constants/api.ts
src/hooks/useTimeTableData.ts
src/pages/DecisionPage.tsx
src/pages/ResultPage.tsx
src/pages/SelectPage.tsx
src/styles/components/container.ts
src/utils/meeting/timetable/formatDateTime.ts

헤더 제거
커스텀 훅 리펙토링
<br/>
<br/>
<br/>

[Feat/HM-145] 서버 api 연동 작업

---

src/components/login/LoginForm.tsx
src/components/newmeeting/LoginNonMember.tsx
src/hooks/useNonMemberMeeting.ts
src/store/meeting/useNonMemberMeeting.ts

비회원 일정 기능 구현 했습니다.
<br/>
<br/>
이런 사소한 실수를... 죄송합니다..ㅎㅎ
<br/>

[Feat/HM-126] 비회원 일정 기능 구현

---

.env
src/components/newmeeting/ShareMeeting.tsx
src/store/meeting/useNonMemberMeeting.ts

- 로그인 오류 수정
- 링크 복사 기능 추가
<br/>
<br/>
- TMI: 로그인 오류는 세종님의 오타 때문이었다
<br/>

[FIX/HM]: 로그인 오류 수정, 링크 복사 기능 추가

---

src/components/meeting/result/ResultTimeTable.tsx

[FIX/HM-145] 배포 오류 수정

---

src/components/meeting/result/ResultTimeTable.tsx
src/components/meeting/timetable/ResultTimeCell.tsx

셀 intensity 계산 로직 수정
<br/>
<br/>
<br/>

[Feat/HM-145] 디자인 수정 및 셀로직 수정

---

vite.config.ts

config 내용 수정
<br/>
<br/>
<br/>

[Feat/HM-145] 리다이렉트 오류 수정

---

src/pages/SelectPage.tsx
vite.config.ts

[Release]: redirect 오류 수정 후 배포

---

src/apis/instance.ts

[FIX]: withCredentials 추가

---

src/apis/instance.ts
src/pages/SelectPage.tsx

[Release]: withCredentials 추가 후 배포

---

src/apis/instance.ts
src/hooks/useLogout.ts

[FIX]: user store 리셋

---

src/apis/instance.ts
src/hooks/useLogout.ts
src/pages/SelectPage.tsx

[Release]: store 리셋, 토큰 재발급 오타 수정

---

src/pages/SelectPage.tsx

[FIX/HM-145] 배포 리다이렉트 수정

---

src/apis/room.api.ts
src/hooks/useMakeMemberMeeting.ts
src/hooks/useRoomList.ts
src/pages/RoomPage.tsx

방 상세조회 배포 이슈 해결 테스팅 입니다.
<br/>
<br/>
<br/>

[Fix/HM-165]: 배포 이슈 해결 테스팅

---

src/apis/room.api.ts
src/hooks/useMakeMemberMeeting.ts
src/hooks/useRoomList.ts
src/pages/RoomPage.tsx
src/pages/SelectPage.tsx

배포이슈 테스팅 입니다.
- 방 및 일정 생성후 방 상세 페이지로 이동시 일정 안보임.
<br/>
<br/>
<br/>

[Fix] 배포이슈 테스팅 수정

---

index.html
src/components/home/UpComming.tsx
src/components/newmeeting/ShareMeeting.tsx
src/components/roomdetail/Attenders.tsx
src/components/roomdetail/CreateNewMeeting.tsx
src/pages/HomePage.tsx
src/pages/RoomPage.tsx
src/styles/theme.ts

배포후 발생한 디자인 이슈를 수정했습니다.
<br/>
<br/>
<br/>

[Style/HM-166] 배포 디자인 수정

---

src/components/meeting/result/UrlShareModal.tsx
src/components/meeting/select/TimeSelectCompModal.tsx
src/components/meeting/timetable/BaseTimeTable.tsx
src/components/meeting/timetable/SelectTimeCell.tsx
src/mocks/data/timeTableData.ts
src/pages/DecisionPage.tsx
src/pages/ResultPage.tsx
src/pages/SelectPage.tsx

모달창 스켈레톤 디자인 수정
<br/>
<br/>
<br/>

[DESIGN]/HM-145 히트맵 디자인 수정 및 스켈레톤 UI생성

---

src/components/login/TeammateLogin.tsx

> 비회원 로그인 리다이렉트 오류 수정
<br/>
<br/>
<br/>

[FIX/HM-170]: 비회원 로그인 리다이렉트 오류 수정

---

src/constants/storage.ts
src/hooks/useSocialLogin.ts

로그인 후 callback 오류 수정
<br/>
<br/>
<br/>

[FIX/HM-170]: callback 오류 수정

---

src/components/login/TeammateLogin.tsx
src/constants/storage.ts
src/hooks/useSocialLogin.ts

[Release]: callback 오류 수정 후 배포

---

src/components/meeting/result/ResultTimeTable.tsx
src/components/meeting/select/SelectableTimeTable.tsx
src/main.tsx

히트맵 로직을 수정했습니다
<br/>
<br/>
<br/>

[FIX/HM-145] 시간생성 히트맵 로직 변경

---

src/apis/user.api.ts

> 멤버 추가 get -> patch 변경
<br/>
<br/>
<br/>

[FIX/HM-170]: 멤버 추가 get -> patch 변경

---

src/pages/RoomPage.tsx

[Fix/HM-169] 방 공유 테스트

---

src/pages/NewMeetingPage.tsx
src/pages/RoomPage.tsx

배포 이슈 수정했습니다.
<br/>
<br/>
<br/>

[Fix/HM-169] 배포 이슈 수정

---

src/hooks/useSocialLogin.ts

방공유 기능 테스팅 입니다.
<br/>
<br/>
<br/>

[Fix/HM-169]: 방 공유 테스팅

---

src/components/roomdetail/NonConfirmList.tsx

비확정 일정 페이지 변경 경로 수정
<br/>
<br/>
<br/>

[Fix/HM-169]: 비확정 일정 페이지 변경 경로 수정

---

src/components/roomdetail/NonConfirmList.tsx
src/hooks/useSocialLogin.ts

[Fix] 비확정 일정 페이지 변경 이슈 해결

---

src/apis/room.api.ts
src/components/roomdetail/ConfirmList.tsx
src/types/room.d.ts

[Fix/HM-169]: 확정 일정 시간 수정

---

src/apis/room.api.ts
src/components/roomdetail/ConfirmList.tsx
src/components/roomdetail/NonConfirmList.tsx
src/types/room.d.ts

[Fix] 확정 일정 날짜 수정

---

src/apis/room.api.ts
src/components/roomdetail/ConfirmList.tsx
src/types/room.d.ts

[Fix] 확정일정 날짜 수정

---

src/store/meeting/useTimeStore.ts

[FIX/HM-145] 히트맵 수정중

---

src/components/meeting/select/HeaderToolTip.tsx
src/components/meeting/timetable/ResultTimeCell.tsx
vite.config.ts

[FIX/HM-145] 히트맵 스크롤 기능 locatorJs 제외 툴팁 디자인 수정

---

src/components/meeting/select/HeaderToolTip.tsx
src/components/meeting/timetable/ResultTimeCell.tsx
src/pages/SelectPage.tsx

[FIX/HM-145] 툴팁 디자인 재수정 및 결과 셀 스크롤 오류 수정

---

src/components/meeting/select/HeaderToolTip.tsx
src/components/meeting/timetable/ResultTimeCell.tsx

[FIX/HM-145] 툴팁 디자인 및 결과 셀 드래그 기능 추가

---

src/components/meeting/select/HeaderToolTip.tsx
src/components/meeting/timetable/ResultTimeCell.tsx

[FIX] 툴팁 디자인 변경 및 결과셀 렌더랑 방식 수정

---

src/components/meeting/timetable/ResultTimeCell.tsx

[FIX/HM-145] 결과셀 수정

---

src/components/meeting/select/HeaderToolTip.tsx
src/components/meeting/timetable/ResultTimeCell.tsx

[FIX] 결과 셀 수정

---

src/components/meeting/timetable/ResultTimeCell.tsx
src/hooks/useExternalBrowserRedirect.ts

[FIX] 인앱 리다이렉트 로직

---

index.html
src/App.tsx

[FIX/HM-145] 리다이렉트 수정
